# Blog settings
permalink: /blog/:title

# Site settings
title: Hey Heather, it's me again.
author: dsl
email: heyheather.itsmeagain@gmail.com
description:
  Becoming a better programmer through words to Heather.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.heyheatheritsmeagain.com" # the base hostname & protocol for your site
twitter_username: dol_liars
github_username:  dolliars

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

plugins:
  - jekyll-feed
